// Code generated by tmpl; DO NOT EDIT.
// https://github.com/benbjohnson/tmpl
//
// Source: ./sst_block_accessor.gen.go.tmpl

package store

import (
	"equinox/storage/codec"
	"equinox/storage/types"
)

func (m *mmapAccessor) readFloatBlock(entry *IndexEntry, values *[]types.FloatValue) ([]types.FloatValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrSSTClosed
	}

	var a []types.FloatValue
	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		for _, dataBlock := range dataBlocks {
			*values, err = codec.DecodeFloatBlock(dataBlock, values)
			if err != nil {
				break
			}
			a = append(a, *values...)
		}
		types.FloatValues(a).Deduplicate()
	}

	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readFloatArrayBlock(entry *IndexEntry, values *types.FloatArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrSSTClosed
	}

	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		values.Timestamps = values.Timestamps[:0]
		values.Values = values.Values[:0]
		for _, dataBlock := range dataBlocks {
			var tmp types.FloatArray
			err = codec.DecodeFloatArrayBlock(dataBlock, &tmp)
			if err != nil {
				break
			}
			values.Merge(&tmp)
		}
	}

	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readIntegerBlock(entry *IndexEntry, values *[]types.IntegerValue) ([]types.IntegerValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrSSTClosed
	}

	var a []types.IntegerValue
	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		for _, dataBlock := range dataBlocks {
			*values, err = codec.DecodeIntegerBlock(dataBlock, values)
			if err != nil {
				break
			}
			a = append(a, *values...)
		}
		types.IntegerValues(a).Deduplicate()
	}

	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readIntegerArrayBlock(entry *IndexEntry, values *types.IntegerArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrSSTClosed
	}

	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		values.Timestamps = values.Timestamps[:0]
		values.Values = values.Values[:0]
		for _, dataBlock := range dataBlocks {
			var tmp types.IntegerArray
			err = codec.DecodeIntegerArrayBlock(dataBlock, &tmp)
			if err != nil {
				break
			}
			values.Merge(&tmp)
		}
	}

	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readUnsignedBlock(entry *IndexEntry, values *[]types.UnsignedValue) ([]types.UnsignedValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrSSTClosed
	}

	var a []types.UnsignedValue
	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		for _, dataBlock := range dataBlocks {
			*values, err = codec.DecodeUnsignedBlock(dataBlock, values)
			if err != nil {
				break
			}
			a = append(a, *values...)
		}
		types.UnsignedValues(a).Deduplicate()
	}

	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readUnsignedArrayBlock(entry *IndexEntry, values *types.UnsignedArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrSSTClosed
	}

	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		values.Timestamps = values.Timestamps[:0]
		values.Values = values.Values[:0]
		for _, dataBlock := range dataBlocks {
			var tmp types.UnsignedArray
			err = codec.DecodeUnsignedArrayBlock(dataBlock, &tmp)
			if err != nil {
				break
			}
			values.Merge(&tmp)
		}
	}

	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readStringBlock(entry *IndexEntry, values *[]types.StringValue) ([]types.StringValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrSSTClosed
	}

	var a []types.StringValue
	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		for _, dataBlock := range dataBlocks {
			*values, err = codec.DecodeStringBlock(dataBlock, values)
			if err != nil {
				break
			}
			a = append(a, *values...)
		}
		types.StringValues(a).Deduplicate()
	}

	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readStringArrayBlock(entry *IndexEntry, values *types.StringArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrSSTClosed
	}

	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		values.Timestamps = values.Timestamps[:0]
		values.Values = values.Values[:0]
		for _, dataBlock := range dataBlocks {
			var tmp types.StringArray
			err = codec.DecodeStringArrayBlock(dataBlock, &tmp)
			if err != nil {
				break
			}
			values.Merge(&tmp)
		}
	}

	m.mu.RUnlock()

	return err
}

func (m *mmapAccessor) readBooleanBlock(entry *IndexEntry, values *[]types.BooleanValue) ([]types.BooleanValue, error) {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return nil, ErrSSTClosed
	}

	var a []types.BooleanValue
	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		for _, dataBlock := range dataBlocks {
			*values, err = codec.DecodeBooleanBlock(dataBlock, values)
			if err != nil {
				break
			}
			a = append(a, *values...)
		}
		types.BooleanValues(a).Deduplicate()
	}

	m.mu.RUnlock()

	if err != nil {
		return nil, err
	}

	return a, nil
}

func (m *mmapAccessor) readBooleanArrayBlock(entry *IndexEntry, values *types.BooleanArray) error {
	m.incAccess()

	m.mu.RLock()
	if int64(len(m.b)) < entry.Offset+int64(entry.Size) {
		m.mu.RUnlock()
		return ErrSSTClosed
	}

	dataBlocks, err := m.vr.ReadDataBlocks(m.b[entry.Offset+4:entry.Offset+int64(entry.Size)], false, nil)
	if err == nil {
		values.Timestamps = values.Timestamps[:0]
		values.Values = values.Values[:0]
		for _, dataBlock := range dataBlocks {
			var tmp types.BooleanArray
			err = codec.DecodeBooleanArrayBlock(dataBlock, &tmp)
			if err != nil {
				break
			}
			values.Merge(&tmp)
		}
	}

	m.mu.RUnlock()

	return err
}
