// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: compact.gen.go.tmpl

package compactor

import (
	"equinox/storage/codec"
	"equinox/storage/types"
	"sort"
)

// merge combines the next set of blocks into merged blocks.
func (it *tsmBatchKeyIterator) mergeFloat() {
	// No blocks left, or pending merged values, we're done
	if len(it.blocks) == 0 && len(it.merged) == 0 && it.mergedFloatValues.Len() == 0 {
		return
	}

	sort.Stable(it.blocks)

	dedup := it.mergedFloatValues.Len() != 0
	if len(it.blocks) > 0 && !dedup {
		// If we have more than one block or any partially tombstoned blocks, we many need to dedup
		dedup = len(it.blocks[0].tombstones) > 0 || it.blocks[0].partiallyRead()

		// Quickly scan each block to see if any overlap with the prior block, if they overlap then
		// we need to dedup as there may be duplicate points now
		for i := 1; !dedup && i < len(it.blocks); i++ {
			dedup = it.blocks[i].partiallyRead() ||
				it.blocks[i].overlapsTimeRange(it.blocks[i-1].minTime, it.blocks[i-1].maxTime) ||
				len(it.blocks[i].tombstones) > 0
		}

	}

	it.merged = it.combineFloat(dedup)
}

// combine returns a new set of blocks using the current blocks in the buffers.  If dedup
// is true, all the blocks will be decoded, dedup and sorted in in order.  If dedup is false,
// only blocks that are smaller than the chunk size will be decoded and combined.
func (it *tsmBatchKeyIterator) combineFloat(dedup bool) blocks {
	// TODO : midify this part
	if dedup {
		for it.mergedFloatValues.Len() < it.size && len(it.blocks) > 0 {
			for len(it.blocks) > 0 && it.blocks[0].read() {
				it.blocks = it.blocks[1:]
			}

			if len(it.blocks) == 0 {
				break
			}
			first := it.blocks[0]
			minTime := first.minTime
			maxTime := first.maxTime

			// Adjust the min time to the start of any overlapping blocks.
			for i := 0; i < len(it.blocks); i++ {
				if it.blocks[i].overlapsTimeRange(minTime, maxTime) && !it.blocks[i].read() {
					if it.blocks[i].minTime < minTime {
						minTime = it.blocks[i].minTime
					}
					if it.blocks[i].maxTime > minTime && it.blocks[i].maxTime < maxTime {
						maxTime = it.blocks[i].maxTime
					}
				}
			}

			// We have some overlapping blocks so decode all, append in order and then dedup
			for i := 0; i < len(it.blocks); i++ {
				if !it.blocks[i].overlapsTimeRange(minTime, maxTime) || it.blocks[i].read() {
					continue
				}

				var v types.FloatArray
				var err error
				if err = codec.DecodeFloatArrayBlock(it.blocks[i].b, &v); err != nil {
					it.handleDecodeError(err, "float")
					return nil
				}

				// Invariant: v.MaxTime() == it.blocks[i].maxTime
				if it.blocks[i].maxTime != v.MaxTime() {
					if maxTime == it.blocks[i].maxTime {
						maxTime = v.MaxTime()
					}
					it.blocks[i].maxTime = v.MaxTime()
				}

				// Remove values we already read
				v.Exclude(it.blocks[i].readMin, it.blocks[i].readMax)

				// Filter out only the values for overlapping block
				v.Include(minTime, maxTime)
				if v.Len() > 0 {
					// Record that we read a subset of the block
					it.blocks[i].markRead(v.MinTime(), v.MaxTime())
				}

				// Apply each tombstone to the block
				for _, ts := range it.blocks[i].tombstones {
					v.Exclude(ts.Min, ts.Max)
				}

				it.mergedFloatValues.Merge(&v)
			}
		}

		// Since we combined multiple blocks, we could have more values than we should put into
		// a single block.  We need to chunk them up into groups and re-encode them.
		return it.chunkFloat(nil)
	}
	var i int

	for ; i < len(it.blocks); i++ {

		// skip this block if it's values were already read
		if it.blocks[i].read() {
			continue
		}

		// if this block is already full, just add it as is
		count, err := codec.BlockCount(it.blocks[i].b)
		if err != nil {
			it.AppendError(err)
			continue
		}

		if count < it.size {
			break
		}

		it.merged = append(it.merged, it.blocks[i])
	}

	if it.fast {
		for i < len(it.blocks) {
			// skip this block if it's values were already read
			if it.blocks[i].read() {
				i++
				continue
			}

			it.merged = append(it.merged, it.blocks[i])
			i++
		}
	}

	// if we only have 1 blocks left, just append it as is and avoid decoding/recoding
	if i == len(it.blocks)-1 {
		if !it.blocks[i].read() {
			it.merged = append(it.merged, it.blocks[i])
		}
		i++
	}

	// The remaining blocks can be combined and we know that they do not overlap and
	// so we can just append each, sort and re-encode.
	for i < len(it.blocks) && it.mergedFloatValues.Len() < it.size {
		if it.blocks[i].read() {
			i++
			continue
		}

		var v types.FloatArray
		if err := codec.DecodeFloatArrayBlock(it.blocks[i].b, &v); err != nil {
			it.handleDecodeError(err, "float")
			return nil
		}

		// Invariant: v.MaxTime() == it.blocks[i].maxTime
		if it.blocks[i].maxTime != v.MaxTime() {
			it.blocks[i].maxTime = v.MaxTime()
		}

		// Apply each tombstone to the block
		for _, ts := range it.blocks[i].tombstones {
			v.Exclude(ts.Min, ts.Max)
		}

		it.blocks[i].markRead(it.blocks[i].minTime, it.blocks[i].maxTime)

		it.mergedFloatValues.Merge(&v)
		i++
	}

	it.blocks = it.blocks[i:]

	return it.chunkFloat(it.merged)
}

// 切块
func (it *tsmBatchKeyIterator) chunkFloat(dst blocks) blocks {
	if it.mergedFloatValues.Len() > it.size {
		var values types.FloatArray
		values.Timestamps = it.mergedFloatValues.Timestamps[:it.size]
		minTime, maxTime := values.Timestamps[0], values.Timestamps[len(values.Timestamps)-1]
		values.Values = it.mergedFloatValues.Values[:it.size]

		cb, err := codec.EncodeFloatArrayBlock(&values, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "float")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedFloatValues.Timestamps = it.mergedFloatValues.Timestamps[it.size:]
		it.mergedFloatValues.Values = it.mergedFloatValues.Values[it.size:]
		return dst
	}

	// Re-encode the remaining values into the last block
	if it.mergedFloatValues.Len() > 0 {
		minTime, maxTime := it.mergedFloatValues.Timestamps[0], it.mergedFloatValues.Timestamps[len(it.mergedFloatValues.Timestamps)-1]
		cb, err := codec.EncodeFloatArrayBlock(it.mergedFloatValues, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "float")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedFloatValues.Timestamps = it.mergedFloatValues.Timestamps[:0]
		it.mergedFloatValues.Values = it.mergedFloatValues.Values[:0]
	}
	return dst
}

// merge combines the next set of blocks into merged blocks.
func (it *tsmBatchKeyIterator) mergeInteger() {
	// No blocks left, or pending merged values, we're done
	if len(it.blocks) == 0 && len(it.merged) == 0 && it.mergedIntegerValues.Len() == 0 {
		return
	}

	sort.Stable(it.blocks)

	dedup := it.mergedIntegerValues.Len() != 0
	if len(it.blocks) > 0 && !dedup {
		// If we have more than one block or any partially tombstoned blocks, we many need to dedup
		dedup = len(it.blocks[0].tombstones) > 0 || it.blocks[0].partiallyRead()

		// Quickly scan each block to see if any overlap with the prior block, if they overlap then
		// we need to dedup as there may be duplicate points now
		for i := 1; !dedup && i < len(it.blocks); i++ {
			dedup = it.blocks[i].partiallyRead() ||
				it.blocks[i].overlapsTimeRange(it.blocks[i-1].minTime, it.blocks[i-1].maxTime) ||
				len(it.blocks[i].tombstones) > 0
		}

	}

	it.merged = it.combineInteger(dedup)
}

// combine returns a new set of blocks using the current blocks in the buffers.  If dedup
// is true, all the blocks will be decoded, dedup and sorted in in order.  If dedup is false,
// only blocks that are smaller than the chunk size will be decoded and combined.
func (it *tsmBatchKeyIterator) combineInteger(dedup bool) blocks {
	if dedup {
		for it.mergedIntegerValues.Len() < it.size && len(it.blocks) > 0 {
			for len(it.blocks) > 0 && it.blocks[0].read() {
				it.blocks = it.blocks[1:]
			}

			if len(it.blocks) == 0 {
				break
			}
			first := it.blocks[0]
			minTime := first.minTime
			maxTime := first.maxTime

			// Adjust the min time to the start of any overlapping blocks.
			for i := 0; i < len(it.blocks); i++ {
				if it.blocks[i].overlapsTimeRange(minTime, maxTime) && !it.blocks[i].read() {
					if it.blocks[i].minTime < minTime {
						minTime = it.blocks[i].minTime
					}
					if it.blocks[i].maxTime > minTime && it.blocks[i].maxTime < maxTime {
						maxTime = it.blocks[i].maxTime
					}
				}
			}

			// We have some overlapping blocks so decode all, append in order and then dedup
			for i := 0; i < len(it.blocks); i++ {
				if !it.blocks[i].overlapsTimeRange(minTime, maxTime) || it.blocks[i].read() {
					continue
				}

				var v types.IntegerArray
				var err error
				if err = codec.DecodeIntegerArrayBlock(it.blocks[i].b, &v); err != nil {
					it.handleDecodeError(err, "integer")
					return nil
				}

				// Invariant: v.MaxTime() == it.blocks[i].maxTime
				if it.blocks[i].maxTime != v.MaxTime() {
					if maxTime == it.blocks[i].maxTime {
						maxTime = v.MaxTime()
					}
					it.blocks[i].maxTime = v.MaxTime()
				}

				// Remove values we already read
				v.Exclude(it.blocks[i].readMin, it.blocks[i].readMax)

				// Filter out only the values for overlapping block
				v.Include(minTime, maxTime)
				if v.Len() > 0 {
					// Record that we read a subset of the block
					it.blocks[i].markRead(v.MinTime(), v.MaxTime())
				}

				// Apply each tombstone to the block
				for _, ts := range it.blocks[i].tombstones {
					v.Exclude(ts.Min, ts.Max)
				}

				it.mergedIntegerValues.Merge(&v)
			}
		}

		// Since we combined multiple blocks, we could have more values than we should put into
		// a single block.  We need to chunk them up into groups and re-encode them.
		return it.chunkInteger(nil)
	}
	var i int

	for ; i < len(it.blocks); i++ {

		// skip this block if it's values were already read
		if it.blocks[i].read() {
			continue
		}

		// if this block is already full, just add it as is
		count, err := codec.BlockCount(it.blocks[i].b)
		if err != nil {
			it.AppendError(err)
			continue
		}

		if count < it.size {
			break
		}

		it.merged = append(it.merged, it.blocks[i])
	}

	if it.fast {
		for i < len(it.blocks) {
			// skip this block if it's values were already read
			if it.blocks[i].read() {
				i++
				continue
			}

			it.merged = append(it.merged, it.blocks[i])
			i++
		}
	}

	// if we only have 1 blocks left, just append it as is and avoid decoding/recoding
	if i == len(it.blocks)-1 {
		if !it.blocks[i].read() {
			it.merged = append(it.merged, it.blocks[i])
		}
		i++
	}

	// The remaining blocks can be combined and we know that they do not overlap and
	// so we can just append each, sort and re-encode.
	for i < len(it.blocks) && it.mergedIntegerValues.Len() < it.size {
		if it.blocks[i].read() {
			i++
			continue
		}

		var v types.IntegerArray
		if err := codec.DecodeIntegerArrayBlock(it.blocks[i].b, &v); err != nil {
			it.handleDecodeError(err, "integer")
			return nil
		}

		// Invariant: v.MaxTime() == it.blocks[i].maxTime
		if it.blocks[i].maxTime != v.MaxTime() {
			it.blocks[i].maxTime = v.MaxTime()
		}

		// Apply each tombstone to the block
		for _, ts := range it.blocks[i].tombstones {
			v.Exclude(ts.Min, ts.Max)
		}

		it.blocks[i].markRead(it.blocks[i].minTime, it.blocks[i].maxTime)

		it.mergedIntegerValues.Merge(&v)
		i++
	}

	it.blocks = it.blocks[i:]

	return it.chunkInteger(it.merged)
}

func (it *tsmBatchKeyIterator) chunkInteger(dst blocks) blocks {
	if it.mergedIntegerValues.Len() > it.size {
		var values types.IntegerArray
		values.Timestamps = it.mergedIntegerValues.Timestamps[:it.size]
		minTime, maxTime := values.Timestamps[0], values.Timestamps[len(values.Timestamps)-1]
		values.Values = it.mergedIntegerValues.Values[:it.size]

		cb, err := codec.EncodeIntegerArrayBlock(&values, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "integer")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedIntegerValues.Timestamps = it.mergedIntegerValues.Timestamps[it.size:]
		it.mergedIntegerValues.Values = it.mergedIntegerValues.Values[it.size:]
		return dst
	}

	// Re-encode the remaining values into the last block
	if it.mergedIntegerValues.Len() > 0 {
		minTime, maxTime := it.mergedIntegerValues.Timestamps[0], it.mergedIntegerValues.Timestamps[len(it.mergedIntegerValues.Timestamps)-1]
		cb, err := codec.EncodeIntegerArrayBlock(it.mergedIntegerValues, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "integer")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedIntegerValues.Timestamps = it.mergedIntegerValues.Timestamps[:0]
		it.mergedIntegerValues.Values = it.mergedIntegerValues.Values[:0]
	}
	return dst
}

// merge combines the next set of blocks into merged blocks.
func (it *tsmBatchKeyIterator) mergeUnsigned() {
	// No blocks left, or pending merged values, we're done
	if len(it.blocks) == 0 && len(it.merged) == 0 && it.mergedUnsignedValues.Len() == 0 {
		return
	}

	sort.Stable(it.blocks)

	dedup := it.mergedUnsignedValues.Len() != 0
	if len(it.blocks) > 0 && !dedup {
		// If we have more than one block or any partially tombstoned blocks, we many need to dedup
		dedup = len(it.blocks[0].tombstones) > 0 || it.blocks[0].partiallyRead()

		// Quickly scan each block to see if any overlap with the prior block, if they overlap then
		// we need to dedup as there may be duplicate points now
		for i := 1; !dedup && i < len(it.blocks); i++ {
			dedup = it.blocks[i].partiallyRead() ||
				it.blocks[i].overlapsTimeRange(it.blocks[i-1].minTime, it.blocks[i-1].maxTime) ||
				len(it.blocks[i].tombstones) > 0
		}

	}

	it.merged = it.combineUnsigned(dedup)
}

// combine returns a new set of blocks using the current blocks in the buffers.  If dedup
// is true, all the blocks will be decoded, dedup and sorted in in order.  If dedup is false,
// only blocks that are smaller than the chunk size will be decoded and combined.
func (it *tsmBatchKeyIterator) combineUnsigned(dedup bool) blocks {
	if dedup {
		for it.mergedUnsignedValues.Len() < it.size && len(it.blocks) > 0 {
			for len(it.blocks) > 0 && it.blocks[0].read() {
				it.blocks = it.blocks[1:]
			}

			if len(it.blocks) == 0 {
				break
			}
			first := it.blocks[0]
			minTime := first.minTime
			maxTime := first.maxTime

			// Adjust the min time to the start of any overlapping blocks.
			for i := 0; i < len(it.blocks); i++ {
				if it.blocks[i].overlapsTimeRange(minTime, maxTime) && !it.blocks[i].read() {
					if it.blocks[i].minTime < minTime {
						minTime = it.blocks[i].minTime
					}
					if it.blocks[i].maxTime > minTime && it.blocks[i].maxTime < maxTime {
						maxTime = it.blocks[i].maxTime
					}
				}
			}

			// We have some overlapping blocks so decode all, append in order and then dedup
			for i := 0; i < len(it.blocks); i++ {
				if !it.blocks[i].overlapsTimeRange(minTime, maxTime) || it.blocks[i].read() {
					continue
				}

				var v types.UnsignedArray
				var err error
				if err = codec.DecodeUnsignedArrayBlock(it.blocks[i].b, &v); err != nil {
					it.handleDecodeError(err, "unsigned")
					return nil
				}

				// Invariant: v.MaxTime() == it.blocks[i].maxTime
				if it.blocks[i].maxTime != v.MaxTime() {
					if maxTime == it.blocks[i].maxTime {
						maxTime = v.MaxTime()
					}
					it.blocks[i].maxTime = v.MaxTime()
				}

				// Remove values we already read
				v.Exclude(it.blocks[i].readMin, it.blocks[i].readMax)

				// Filter out only the values for overlapping block
				v.Include(minTime, maxTime)
				if v.Len() > 0 {
					// Record that we read a subset of the block
					it.blocks[i].markRead(v.MinTime(), v.MaxTime())
				}

				// Apply each tombstone to the block
				for _, ts := range it.blocks[i].tombstones {
					v.Exclude(ts.Min, ts.Max)
				}

				it.mergedUnsignedValues.Merge(&v)
			}
		}

		// Since we combined multiple blocks, we could have more values than we should put into
		// a single block.  We need to chunk them up into groups and re-encode them.
		return it.chunkUnsigned(nil)
	}
	var i int

	for ; i < len(it.blocks); i++ {

		// skip this block if it's values were already read
		if it.blocks[i].read() {
			continue
		}

		// if this block is already full, just add it as is
		count, err := codec.BlockCount(it.blocks[i].b)
		if err != nil {
			it.AppendError(err)
			continue
		}

		if count < it.size {
			break
		}

		it.merged = append(it.merged, it.blocks[i])
	}

	if it.fast {
		for i < len(it.blocks) {
			// skip this block if it's values were already read
			if it.blocks[i].read() {
				i++
				continue
			}

			it.merged = append(it.merged, it.blocks[i])
			i++
		}
	}

	// if we only have 1 blocks left, just append it as is and avoid decoding/recoding
	if i == len(it.blocks)-1 {
		if !it.blocks[i].read() {
			it.merged = append(it.merged, it.blocks[i])
		}
		i++
	}

	// The remaining blocks can be combined and we know that they do not overlap and
	// so we can just append each, sort and re-encode.
	for i < len(it.blocks) && it.mergedUnsignedValues.Len() < it.size {
		if it.blocks[i].read() {
			i++
			continue
		}

		var v types.UnsignedArray
		if err := codec.DecodeUnsignedArrayBlock(it.blocks[i].b, &v); err != nil {
			it.handleDecodeError(err, "unsigned")
			return nil
		}

		// Invariant: v.MaxTime() == it.blocks[i].maxTime
		if it.blocks[i].maxTime != v.MaxTime() {
			it.blocks[i].maxTime = v.MaxTime()
		}

		// Apply each tombstone to the block
		for _, ts := range it.blocks[i].tombstones {
			v.Exclude(ts.Min, ts.Max)
		}

		it.blocks[i].markRead(it.blocks[i].minTime, it.blocks[i].maxTime)

		it.mergedUnsignedValues.Merge(&v)
		i++
	}

	it.blocks = it.blocks[i:]

	return it.chunkUnsigned(it.merged)
}

func (it *tsmBatchKeyIterator) chunkUnsigned(dst blocks) blocks {
	if it.mergedUnsignedValues.Len() > it.size {
		var values types.UnsignedArray
		values.Timestamps = it.mergedUnsignedValues.Timestamps[:it.size]
		minTime, maxTime := values.Timestamps[0], values.Timestamps[len(values.Timestamps)-1]
		values.Values = it.mergedUnsignedValues.Values[:it.size]

		cb, err := codec.EncodeUnsignedArrayBlock(&values, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "unsigned")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedUnsignedValues.Timestamps = it.mergedUnsignedValues.Timestamps[it.size:]
		it.mergedUnsignedValues.Values = it.mergedUnsignedValues.Values[it.size:]
		return dst
	}

	// Re-encode the remaining values into the last block
	if it.mergedUnsignedValues.Len() > 0 {
		minTime, maxTime := it.mergedUnsignedValues.Timestamps[0], it.mergedUnsignedValues.Timestamps[len(it.mergedUnsignedValues.Timestamps)-1]
		cb, err := codec.EncodeUnsignedArrayBlock(it.mergedUnsignedValues, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "unsigned")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedUnsignedValues.Timestamps = it.mergedUnsignedValues.Timestamps[:0]
		it.mergedUnsignedValues.Values = it.mergedUnsignedValues.Values[:0]
	}
	return dst
}

// merge combines the next set of blocks into merged blocks.
func (it *tsmBatchKeyIterator) mergeString() {
	// No blocks left, or pending merged values, we're done
	if len(it.blocks) == 0 && len(it.merged) == 0 && it.mergedStringValues.Len() == 0 {
		return
	}

	sort.Stable(it.blocks)

	dedup := it.mergedStringValues.Len() != 0
	if len(it.blocks) > 0 && !dedup {
		// If we have more than one block or any partially tombstoned blocks, we many need to dedup
		dedup = len(it.blocks[0].tombstones) > 0 || it.blocks[0].partiallyRead()

		// Quickly scan each block to see if any overlap with the prior block, if they overlap then
		// we need to dedup as there may be duplicate points now
		for i := 1; !dedup && i < len(it.blocks); i++ {
			dedup = it.blocks[i].partiallyRead() ||
				it.blocks[i].overlapsTimeRange(it.blocks[i-1].minTime, it.blocks[i-1].maxTime) ||
				len(it.blocks[i].tombstones) > 0
		}

	}

	it.merged = it.combineString(dedup)
}

// combine returns a new set of blocks using the current blocks in the buffers.  If dedup
// is true, all the blocks will be decoded, dedup and sorted in in order.  If dedup is false,
// only blocks that are smaller than the chunk size will be decoded and combined.
func (it *tsmBatchKeyIterator) combineString(dedup bool) blocks {
	if dedup {
		for it.mergedStringValues.Len() < it.size && len(it.blocks) > 0 {
			for len(it.blocks) > 0 && it.blocks[0].read() {
				it.blocks = it.blocks[1:]
			}

			if len(it.blocks) == 0 {
				break
			}
			first := it.blocks[0]
			minTime := first.minTime
			maxTime := first.maxTime

			// Adjust the min time to the start of any overlapping blocks.
			for i := 0; i < len(it.blocks); i++ {
				if it.blocks[i].overlapsTimeRange(minTime, maxTime) && !it.blocks[i].read() {
					if it.blocks[i].minTime < minTime {
						minTime = it.blocks[i].minTime
					}
					if it.blocks[i].maxTime > minTime && it.blocks[i].maxTime < maxTime {
						maxTime = it.blocks[i].maxTime
					}
				}
			}

			// We have some overlapping blocks so decode all, append in order and then dedup
			for i := 0; i < len(it.blocks); i++ {
				if !it.blocks[i].overlapsTimeRange(minTime, maxTime) || it.blocks[i].read() {
					continue
				}

				var v types.StringArray
				var err error
				if err = codec.DecodeStringArrayBlock(it.blocks[i].b, &v); err != nil {
					it.handleDecodeError(err, "string")
					return nil
				}

				// Invariant: v.MaxTime() == it.blocks[i].maxTime
				if it.blocks[i].maxTime != v.MaxTime() {
					if maxTime == it.blocks[i].maxTime {
						maxTime = v.MaxTime()
					}
					it.blocks[i].maxTime = v.MaxTime()
				}

				// Remove values we already read
				v.Exclude(it.blocks[i].readMin, it.blocks[i].readMax)

				// Filter out only the values for overlapping block
				v.Include(minTime, maxTime)
				if v.Len() > 0 {
					// Record that we read a subset of the block
					it.blocks[i].markRead(v.MinTime(), v.MaxTime())
				}

				// Apply each tombstone to the block
				for _, ts := range it.blocks[i].tombstones {
					v.Exclude(ts.Min, ts.Max)
				}

				it.mergedStringValues.Merge(&v)
			}
		}

		// Since we combined multiple blocks, we could have more values than we should put into
		// a single block.  We need to chunk them up into groups and re-encode them.
		return it.chunkString(nil)
	}
	var i int

	for ; i < len(it.blocks); i++ {

		// skip this block if it's values were already read
		if it.blocks[i].read() {
			continue
		}

		// if this block is already full, just add it as is
		count, err := codec.BlockCount(it.blocks[i].b)
		if err != nil {
			it.AppendError(err)
			continue
		}

		if count < it.size {
			break
		}

		it.merged = append(it.merged, it.blocks[i])
	}

	if it.fast {
		for i < len(it.blocks) {
			// skip this block if it's values were already read
			if it.blocks[i].read() {
				i++
				continue
			}

			it.merged = append(it.merged, it.blocks[i])
			i++
		}
	}

	// if we only have 1 blocks left, just append it as is and avoid decoding/recoding
	if i == len(it.blocks)-1 {
		if !it.blocks[i].read() {
			it.merged = append(it.merged, it.blocks[i])
		}
		i++
	}

	// The remaining blocks can be combined and we know that they do not overlap and
	// so we can just append each, sort and re-encode.
	for i < len(it.blocks) && it.mergedStringValues.Len() < it.size {
		if it.blocks[i].read() {
			i++
			continue
		}

		var v types.StringArray
		if err := codec.DecodeStringArrayBlock(it.blocks[i].b, &v); err != nil {
			it.handleDecodeError(err, "string")
			return nil
		}

		// Invariant: v.MaxTime() == it.blocks[i].maxTime
		if it.blocks[i].maxTime != v.MaxTime() {
			it.blocks[i].maxTime = v.MaxTime()
		}

		// Apply each tombstone to the block
		for _, ts := range it.blocks[i].tombstones {
			v.Exclude(ts.Min, ts.Max)
		}

		it.blocks[i].markRead(it.blocks[i].minTime, it.blocks[i].maxTime)

		it.mergedStringValues.Merge(&v)
		i++
	}

	it.blocks = it.blocks[i:]

	return it.chunkString(it.merged)
}

func (it *tsmBatchKeyIterator) chunkString(dst blocks) blocks {
	if it.mergedStringValues.Len() > it.size {
		var values types.StringArray
		values.Timestamps = it.mergedStringValues.Timestamps[:it.size]
		minTime, maxTime := values.Timestamps[0], values.Timestamps[len(values.Timestamps)-1]
		values.Values = it.mergedStringValues.Values[:it.size]

		cb, err := codec.EncodeStringArrayBlock(&values, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "string")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedStringValues.Timestamps = it.mergedStringValues.Timestamps[it.size:]
		it.mergedStringValues.Values = it.mergedStringValues.Values[it.size:]
		return dst
	}

	// Re-encode the remaining values into the last block
	if it.mergedStringValues.Len() > 0 {
		minTime, maxTime := it.mergedStringValues.Timestamps[0], it.mergedStringValues.Timestamps[len(it.mergedStringValues.Timestamps)-1]
		cb, err := codec.EncodeStringArrayBlock(it.mergedStringValues, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "string")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedStringValues.Timestamps = it.mergedStringValues.Timestamps[:0]
		it.mergedStringValues.Values = it.mergedStringValues.Values[:0]
	}
	return dst
}

// merge combines the next set of blocks into merged blocks.
func (it *tsmBatchKeyIterator) mergeBoolean() {
	// No blocks left, or pending merged values, we're done
	if len(it.blocks) == 0 && len(it.merged) == 0 && it.mergedBooleanValues.Len() == 0 {
		return
	}

	sort.Stable(it.blocks)

	dedup := it.mergedBooleanValues.Len() != 0
	if len(it.blocks) > 0 && !dedup {
		// If we have more than one block or any partially tombstoned blocks, we many need to dedup
		dedup = len(it.blocks[0].tombstones) > 0 || it.blocks[0].partiallyRead()

		// Quickly scan each block to see if any overlap with the prior block, if they overlap then
		// we need to dedup as there may be duplicate points now
		for i := 1; !dedup && i < len(it.blocks); i++ {
			dedup = it.blocks[i].partiallyRead() ||
				it.blocks[i].overlapsTimeRange(it.blocks[i-1].minTime, it.blocks[i-1].maxTime) ||
				len(it.blocks[i].tombstones) > 0
		}

	}

	it.merged = it.combineBoolean(dedup)
}

// combine returns a new set of blocks using the current blocks in the buffers.  If dedup
// is true, all the blocks will be decoded, dedup and sorted in in order.  If dedup is false,
// only blocks that are smaller than the chunk size will be decoded and combined.
func (it *tsmBatchKeyIterator) combineBoolean(dedup bool) blocks {
	if dedup {
		for it.mergedBooleanValues.Len() < it.size && len(it.blocks) > 0 {
			for len(it.blocks) > 0 && it.blocks[0].read() {
				it.blocks = it.blocks[1:]
			}

			if len(it.blocks) == 0 {
				break
			}
			first := it.blocks[0]
			minTime := first.minTime
			maxTime := first.maxTime

			// Adjust the min time to the start of any overlapping blocks.
			for i := 0; i < len(it.blocks); i++ {
				if it.blocks[i].overlapsTimeRange(minTime, maxTime) && !it.blocks[i].read() {
					if it.blocks[i].minTime < minTime {
						minTime = it.blocks[i].minTime
					}
					if it.blocks[i].maxTime > minTime && it.blocks[i].maxTime < maxTime {
						maxTime = it.blocks[i].maxTime
					}
				}
			}

			// We have some overlapping blocks so decode all, append in order and then dedup
			for i := 0; i < len(it.blocks); i++ {
				if !it.blocks[i].overlapsTimeRange(minTime, maxTime) || it.blocks[i].read() {
					continue
				}

				var v types.BooleanArray
				var err error
				if err = codec.DecodeBooleanArrayBlock(it.blocks[i].b, &v); err != nil {
					it.handleDecodeError(err, "boolean")
					return nil
				}

				// Invariant: v.MaxTime() == it.blocks[i].maxTime
				if it.blocks[i].maxTime != v.MaxTime() {
					if maxTime == it.blocks[i].maxTime {
						maxTime = v.MaxTime()
					}
					it.blocks[i].maxTime = v.MaxTime()
				}

				// Remove values we already read
				v.Exclude(it.blocks[i].readMin, it.blocks[i].readMax)

				// Filter out only the values for overlapping block
				v.Include(minTime, maxTime)
				if v.Len() > 0 {
					// Record that we read a subset of the block
					it.blocks[i].markRead(v.MinTime(), v.MaxTime())
				}

				// Apply each tombstone to the block
				for _, ts := range it.blocks[i].tombstones {
					v.Exclude(ts.Min, ts.Max)
				}

				it.mergedBooleanValues.Merge(&v)
			}
		}

		// Since we combined multiple blocks, we could have more values than we should put into
		// a single block.  We need to chunk them up into groups and re-encode them.
		return it.chunkBoolean(nil)
	}
	var i int

	for ; i < len(it.blocks); i++ {

		// skip this block if it's values were already read
		if it.blocks[i].read() {
			continue
		}

		// if this block is already full, just add it as is
		count, err := codec.BlockCount(it.blocks[i].b)
		if err != nil {
			it.AppendError(err)
			continue
		}

		if count < it.size {
			break
		}

		it.merged = append(it.merged, it.blocks[i])
	}

	if it.fast {
		for i < len(it.blocks) {
			// skip this block if it's values were already read
			if it.blocks[i].read() {
				i++
				continue
			}

			it.merged = append(it.merged, it.blocks[i])
			i++
		}
	}

	// if we only have 1 blocks left, just append it as is and avoid decoding/recoding
	if i == len(it.blocks)-1 {
		if !it.blocks[i].read() {
			it.merged = append(it.merged, it.blocks[i])
		}
		i++
	}

	// The remaining blocks can be combined and we know that they do not overlap and
	// so we can just append each, sort and re-encode.
	for i < len(it.blocks) && it.mergedBooleanValues.Len() < it.size {
		if it.blocks[i].read() {
			i++
			continue
		}

		var v types.BooleanArray
		if err := codec.DecodeBooleanArrayBlock(it.blocks[i].b, &v); err != nil {
			it.handleDecodeError(err, "boolean")
			return nil
		}

		// Invariant: v.MaxTime() == it.blocks[i].maxTime
		if it.blocks[i].maxTime != v.MaxTime() {
			it.blocks[i].maxTime = v.MaxTime()
		}

		// Apply each tombstone to the block
		for _, ts := range it.blocks[i].tombstones {
			v.Exclude(ts.Min, ts.Max)
		}

		it.blocks[i].markRead(it.blocks[i].minTime, it.blocks[i].maxTime)

		it.mergedBooleanValues.Merge(&v)
		i++
	}

	it.blocks = it.blocks[i:]

	return it.chunkBoolean(it.merged)
}

func (it *tsmBatchKeyIterator) chunkBoolean(dst blocks) blocks {
	if it.mergedBooleanValues.Len() > it.size {
		var values types.BooleanArray
		values.Timestamps = it.mergedBooleanValues.Timestamps[:it.size]
		minTime, maxTime := values.Timestamps[0], values.Timestamps[len(values.Timestamps)-1]
		values.Values = it.mergedBooleanValues.Values[:it.size]

		cb, err := codec.EncodeBooleanArrayBlock(&values, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "boolean")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedBooleanValues.Timestamps = it.mergedBooleanValues.Timestamps[it.size:]
		it.mergedBooleanValues.Values = it.mergedBooleanValues.Values[it.size:]
		return dst
	}

	// Re-encode the remaining values into the last block
	if it.mergedBooleanValues.Len() > 0 {
		minTime, maxTime := it.mergedBooleanValues.Timestamps[0], it.mergedBooleanValues.Timestamps[len(it.mergedBooleanValues.Timestamps)-1]
		cb, err := codec.EncodeBooleanArrayBlock(it.mergedBooleanValues, nil) // TODO(edd): pool this buffer
		if err != nil {
			it.handleEncodeError(err, "boolean")
			return nil
		}

		dst = append(dst, &block{
			minTime: minTime,
			maxTime: maxTime,
			key:     it.key,
			b:       cb,
		})
		it.mergedBooleanValues.Timestamps = it.mergedBooleanValues.Timestamps[:0]
		it.mergedBooleanValues.Values = it.mergedBooleanValues.Values[:0]
	}
	return dst
}
