// Code generated by tmpl; DO NOT EDIT.
// https://github.com/benbjohnson/tmpl
//
// Source: ./array_cursor.gen.go.tmpl

package cursor

import (
	"equinox/storage/config"
	"equinox/storage/store"
	"equinox/storage/types"
	"sort"
)

// Array Cursors

type FloatArrayAscendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.FloatArray
		values    *types.FloatArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.FloatArray
}

func NewFloatArrayAscendingCursor() *FloatArrayAscendingCursor {
	c := &FloatArrayAscendingCursor{
		res: types.NewFloatArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewFloatArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *FloatArrayAscendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() >= seek
	})

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadFloatArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] >= seek
	})
}

func (c *FloatArrayAscendingCursor) Err() error { return nil }

// close closes the cursor and any dependent cursors.
func (c *FloatArrayAscendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

// Next returns the next key/value for the cursor.
func (c *FloatArrayAscendingCursor) Next() *types.FloatArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos < len(tvals.Timestamps) && c.cache.pos < len(cvals) {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.FloatValue).RawValue()
			c.cache.pos++
			c.sst.pos++
		} else if ckey < tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.FloatValue).RawValue()
			c.cache.pos++
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos++
		}

		pos++

		if c.sst.pos >= len(tvals.Timestamps) {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		if c.sst.pos < len(tvals.Timestamps) {
			if pos == 0 && len(c.res.Timestamps) >= len(tvals.Timestamps) {
				// optimization: all points can be served from SST data because
				// we need the entire block and the block completely fits within
				// the buffer.
				copy(c.res.Timestamps, tvals.Timestamps)
				pos += copy(c.res.Values, tvals.Values)
				c.nextSST()
			} else {
				// copy as much as we can
				n := copy(c.res.Timestamps[pos:], tvals.Timestamps[c.sst.pos:])
				copy(c.res.Values[pos:], tvals.Values[c.sst.pos:])
				pos += n
				c.sst.pos += n
				if c.sst.pos >= len(tvals.Timestamps) {
					c.nextSST()
				}
			}
		}

		if c.cache.pos < len(cvals) {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos < len(cvals) {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.FloatValue).RawValue()
				pos++
				c.cache.pos++
			}
		}
	}

	// Strip timestamps from after the end time.
	if pos > 0 && c.res.Timestamps[pos-1] > c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] > c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *FloatArrayAscendingCursor) nextSST() *types.FloatArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadFloatArrayBlock(c.sst.buf)
	c.sst.pos = 0
	return c.sst.values
}

type FloatArrayDescendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.FloatArray
		values    *types.FloatArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.FloatArray
}

func NewFloatArrayDescendingCursor() *FloatArrayDescendingCursor {
	c := &FloatArrayDescendingCursor{
		res: types.NewFloatArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewFloatArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *FloatArrayDescendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	// Search for the time value greater than the seek time (not included)
	// and then move our position back one which will include the values in
	// our time range.
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() > seek
	})
	c.cache.pos--

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadFloatArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] > seek
	})
	c.sst.pos--
}

func (c *FloatArrayDescendingCursor) Err() error { return nil }

func (c *FloatArrayDescendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

func (c *FloatArrayDescendingCursor) Next() *types.FloatArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos >= 0 && c.cache.pos >= 0 {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.FloatValue).RawValue()
			c.cache.pos--
			c.sst.pos--
		} else if ckey > tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.FloatValue).RawValue()
			c.cache.pos--
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos--
		}

		pos++

		if c.sst.pos < 0 {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		// cache was exhausted
		if c.sst.pos >= 0 {
			for pos < len(c.res.Timestamps) && c.sst.pos >= 0 {
				c.res.Timestamps[pos] = tvals.Timestamps[c.sst.pos]
				c.res.Values[pos] = tvals.Values[c.sst.pos]
				pos++
				c.sst.pos--
				if c.sst.pos < 0 {
					tvals = c.nextSST()
				}
			}
		}

		if c.cache.pos >= 0 {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos >= 0 {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.FloatValue).RawValue()
				pos++
				c.cache.pos--
			}
		}
	}

	// Strip timestamps from before the end time.
	if pos > 0 && c.res.Timestamps[pos-1] < c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] < c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *FloatArrayDescendingCursor) nextSST() *types.FloatArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadFloatArrayBlock(c.sst.buf)
	c.sst.pos = len(c.sst.values.Timestamps) - 1
	return c.sst.values
}

type IntegerArrayAscendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.IntegerArray
		values    *types.IntegerArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.IntegerArray
}

func NewIntegerArrayAscendingCursor() *IntegerArrayAscendingCursor {
	c := &IntegerArrayAscendingCursor{
		res: types.NewIntegerArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewIntegerArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *IntegerArrayAscendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() >= seek
	})

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadIntegerArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] >= seek
	})
}

func (c *IntegerArrayAscendingCursor) Err() error { return nil }

// close closes the cursor and any dependent cursors.
func (c *IntegerArrayAscendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

// Next returns the next key/value for the cursor.
func (c *IntegerArrayAscendingCursor) Next() *types.IntegerArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos < len(tvals.Timestamps) && c.cache.pos < len(cvals) {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.IntegerValue).RawValue()
			c.cache.pos++
			c.sst.pos++
		} else if ckey < tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.IntegerValue).RawValue()
			c.cache.pos++
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos++
		}

		pos++

		if c.sst.pos >= len(tvals.Timestamps) {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		if c.sst.pos < len(tvals.Timestamps) {
			if pos == 0 && len(c.res.Timestamps) >= len(tvals.Timestamps) {
				// optimization: all points can be served from SST data because
				// we need the entire block and the block completely fits within
				// the buffer.
				copy(c.res.Timestamps, tvals.Timestamps)
				pos += copy(c.res.Values, tvals.Values)
				c.nextSST()
			} else {
				// copy as much as we can
				n := copy(c.res.Timestamps[pos:], tvals.Timestamps[c.sst.pos:])
				copy(c.res.Values[pos:], tvals.Values[c.sst.pos:])
				pos += n
				c.sst.pos += n
				if c.sst.pos >= len(tvals.Timestamps) {
					c.nextSST()
				}
			}
		}

		if c.cache.pos < len(cvals) {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos < len(cvals) {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.IntegerValue).RawValue()
				pos++
				c.cache.pos++
			}
		}
	}

	// Strip timestamps from after the end time.
	if pos > 0 && c.res.Timestamps[pos-1] > c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] > c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *IntegerArrayAscendingCursor) nextSST() *types.IntegerArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadIntegerArrayBlock(c.sst.buf)
	c.sst.pos = 0
	return c.sst.values
}

type IntegerArrayDescendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.IntegerArray
		values    *types.IntegerArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.IntegerArray
}

func NewIntegerArrayDescendingCursor() *IntegerArrayDescendingCursor {
	c := &IntegerArrayDescendingCursor{
		res: types.NewIntegerArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewIntegerArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *IntegerArrayDescendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	// Search for the time value greater than the seek time (not included)
	// and then move our position back one which will include the values in
	// our time range.
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() > seek
	})
	c.cache.pos--

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadIntegerArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] > seek
	})
	c.sst.pos--
}

func (c *IntegerArrayDescendingCursor) Err() error { return nil }

func (c *IntegerArrayDescendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

func (c *IntegerArrayDescendingCursor) Next() *types.IntegerArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos >= 0 && c.cache.pos >= 0 {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.IntegerValue).RawValue()
			c.cache.pos--
			c.sst.pos--
		} else if ckey > tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.IntegerValue).RawValue()
			c.cache.pos--
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos--
		}

		pos++

		if c.sst.pos < 0 {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		// cache was exhausted
		if c.sst.pos >= 0 {
			for pos < len(c.res.Timestamps) && c.sst.pos >= 0 {
				c.res.Timestamps[pos] = tvals.Timestamps[c.sst.pos]
				c.res.Values[pos] = tvals.Values[c.sst.pos]
				pos++
				c.sst.pos--
				if c.sst.pos < 0 {
					tvals = c.nextSST()
				}
			}
		}

		if c.cache.pos >= 0 {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos >= 0 {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.IntegerValue).RawValue()
				pos++
				c.cache.pos--
			}
		}
	}

	// Strip timestamps from before the end time.
	if pos > 0 && c.res.Timestamps[pos-1] < c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] < c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *IntegerArrayDescendingCursor) nextSST() *types.IntegerArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadIntegerArrayBlock(c.sst.buf)
	c.sst.pos = len(c.sst.values.Timestamps) - 1
	return c.sst.values
}

type UnsignedArrayAscendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.UnsignedArray
		values    *types.UnsignedArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.UnsignedArray
}

func NewUnsignedArrayAscendingCursor() *UnsignedArrayAscendingCursor {
	c := &UnsignedArrayAscendingCursor{
		res: types.NewUnsignedArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewUnsignedArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *UnsignedArrayAscendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() >= seek
	})

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadUnsignedArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] >= seek
	})
}

func (c *UnsignedArrayAscendingCursor) Err() error { return nil }

// close closes the cursor and any dependent cursors.
func (c *UnsignedArrayAscendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

// Next returns the next key/value for the cursor.
func (c *UnsignedArrayAscendingCursor) Next() *types.UnsignedArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos < len(tvals.Timestamps) && c.cache.pos < len(cvals) {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.UnsignedValue).RawValue()
			c.cache.pos++
			c.sst.pos++
		} else if ckey < tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.UnsignedValue).RawValue()
			c.cache.pos++
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos++
		}

		pos++

		if c.sst.pos >= len(tvals.Timestamps) {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		if c.sst.pos < len(tvals.Timestamps) {
			if pos == 0 && len(c.res.Timestamps) >= len(tvals.Timestamps) {
				// optimization: all points can be served from SST data because
				// we need the entire block and the block completely fits within
				// the buffer.
				copy(c.res.Timestamps, tvals.Timestamps)
				pos += copy(c.res.Values, tvals.Values)
				c.nextSST()
			} else {
				// copy as much as we can
				n := copy(c.res.Timestamps[pos:], tvals.Timestamps[c.sst.pos:])
				copy(c.res.Values[pos:], tvals.Values[c.sst.pos:])
				pos += n
				c.sst.pos += n
				if c.sst.pos >= len(tvals.Timestamps) {
					c.nextSST()
				}
			}
		}

		if c.cache.pos < len(cvals) {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos < len(cvals) {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.UnsignedValue).RawValue()
				pos++
				c.cache.pos++
			}
		}
	}

	// Strip timestamps from after the end time.
	if pos > 0 && c.res.Timestamps[pos-1] > c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] > c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *UnsignedArrayAscendingCursor) nextSST() *types.UnsignedArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadUnsignedArrayBlock(c.sst.buf)
	c.sst.pos = 0
	return c.sst.values
}

type UnsignedArrayDescendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.UnsignedArray
		values    *types.UnsignedArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.UnsignedArray
}

func NewUnsignedArrayDescendingCursor() *UnsignedArrayDescendingCursor {
	c := &UnsignedArrayDescendingCursor{
		res: types.NewUnsignedArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewUnsignedArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *UnsignedArrayDescendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	// Search for the time value greater than the seek time (not included)
	// and then move our position back one which will include the values in
	// our time range.
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() > seek
	})
	c.cache.pos--

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadUnsignedArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] > seek
	})
	c.sst.pos--
}

func (c *UnsignedArrayDescendingCursor) Err() error { return nil }

func (c *UnsignedArrayDescendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

func (c *UnsignedArrayDescendingCursor) Next() *types.UnsignedArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos >= 0 && c.cache.pos >= 0 {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.UnsignedValue).RawValue()
			c.cache.pos--
			c.sst.pos--
		} else if ckey > tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.UnsignedValue).RawValue()
			c.cache.pos--
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos--
		}

		pos++

		if c.sst.pos < 0 {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		// cache was exhausted
		if c.sst.pos >= 0 {
			for pos < len(c.res.Timestamps) && c.sst.pos >= 0 {
				c.res.Timestamps[pos] = tvals.Timestamps[c.sst.pos]
				c.res.Values[pos] = tvals.Values[c.sst.pos]
				pos++
				c.sst.pos--
				if c.sst.pos < 0 {
					tvals = c.nextSST()
				}
			}
		}

		if c.cache.pos >= 0 {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos >= 0 {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.UnsignedValue).RawValue()
				pos++
				c.cache.pos--
			}
		}
	}

	// Strip timestamps from before the end time.
	if pos > 0 && c.res.Timestamps[pos-1] < c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] < c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *UnsignedArrayDescendingCursor) nextSST() *types.UnsignedArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadUnsignedArrayBlock(c.sst.buf)
	c.sst.pos = len(c.sst.values.Timestamps) - 1
	return c.sst.values
}

type StringArrayAscendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.StringArray
		values    *types.StringArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.StringArray
}

func NewStringArrayAscendingCursor() *StringArrayAscendingCursor {
	c := &StringArrayAscendingCursor{
		res: types.NewStringArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewStringArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *StringArrayAscendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() >= seek
	})

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadStringArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] >= seek
	})
}

func (c *StringArrayAscendingCursor) Err() error { return nil }

// close closes the cursor and any dependent cursors.
func (c *StringArrayAscendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

// Next returns the next key/value for the cursor.
func (c *StringArrayAscendingCursor) Next() *types.StringArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos < len(tvals.Timestamps) && c.cache.pos < len(cvals) {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.StringValue).RawValue()
			c.cache.pos++
			c.sst.pos++
		} else if ckey < tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.StringValue).RawValue()
			c.cache.pos++
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos++
		}

		pos++

		if c.sst.pos >= len(tvals.Timestamps) {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		if c.sst.pos < len(tvals.Timestamps) {
			if pos == 0 && len(c.res.Timestamps) >= len(tvals.Timestamps) {
				// optimization: all points can be served from SST data because
				// we need the entire block and the block completely fits within
				// the buffer.
				copy(c.res.Timestamps, tvals.Timestamps)
				pos += copy(c.res.Values, tvals.Values)
				c.nextSST()
			} else {
				// copy as much as we can
				n := copy(c.res.Timestamps[pos:], tvals.Timestamps[c.sst.pos:])
				copy(c.res.Values[pos:], tvals.Values[c.sst.pos:])
				pos += n
				c.sst.pos += n
				if c.sst.pos >= len(tvals.Timestamps) {
					c.nextSST()
				}
			}
		}

		if c.cache.pos < len(cvals) {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos < len(cvals) {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.StringValue).RawValue()
				pos++
				c.cache.pos++
			}
		}
	}

	// Strip timestamps from after the end time.
	if pos > 0 && c.res.Timestamps[pos-1] > c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] > c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *StringArrayAscendingCursor) nextSST() *types.StringArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadStringArrayBlock(c.sst.buf)
	c.sst.pos = 0
	return c.sst.values
}

type StringArrayDescendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.StringArray
		values    *types.StringArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.StringArray
}

func NewStringArrayDescendingCursor() *StringArrayDescendingCursor {
	c := &StringArrayDescendingCursor{
		res: types.NewStringArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewStringArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *StringArrayDescendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	// Search for the time value greater than the seek time (not included)
	// and then move our position back one which will include the values in
	// our time range.
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() > seek
	})
	c.cache.pos--

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadStringArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] > seek
	})
	c.sst.pos--
}

func (c *StringArrayDescendingCursor) Err() error { return nil }

func (c *StringArrayDescendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

func (c *StringArrayDescendingCursor) Next() *types.StringArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos >= 0 && c.cache.pos >= 0 {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.StringValue).RawValue()
			c.cache.pos--
			c.sst.pos--
		} else if ckey > tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.StringValue).RawValue()
			c.cache.pos--
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos--
		}

		pos++

		if c.sst.pos < 0 {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		// cache was exhausted
		if c.sst.pos >= 0 {
			for pos < len(c.res.Timestamps) && c.sst.pos >= 0 {
				c.res.Timestamps[pos] = tvals.Timestamps[c.sst.pos]
				c.res.Values[pos] = tvals.Values[c.sst.pos]
				pos++
				c.sst.pos--
				if c.sst.pos < 0 {
					tvals = c.nextSST()
				}
			}
		}

		if c.cache.pos >= 0 {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos >= 0 {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.StringValue).RawValue()
				pos++
				c.cache.pos--
			}
		}
	}

	// Strip timestamps from before the end time.
	if pos > 0 && c.res.Timestamps[pos-1] < c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] < c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *StringArrayDescendingCursor) nextSST() *types.StringArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadStringArrayBlock(c.sst.buf)
	c.sst.pos = len(c.sst.values.Timestamps) - 1
	return c.sst.values
}

type BooleanArrayAscendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.BooleanArray
		values    *types.BooleanArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.BooleanArray
}

func NewBooleanArrayAscendingCursor() *BooleanArrayAscendingCursor {
	c := &BooleanArrayAscendingCursor{
		res: types.NewBooleanArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewBooleanArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *BooleanArrayAscendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() >= seek
	})

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadBooleanArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] >= seek
	})
}

func (c *BooleanArrayAscendingCursor) Err() error { return nil }

// close closes the cursor and any dependent cursors.
func (c *BooleanArrayAscendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

// Next returns the next key/value for the cursor.
func (c *BooleanArrayAscendingCursor) Next() *types.BooleanArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos < len(tvals.Timestamps) && c.cache.pos < len(cvals) {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.BooleanValue).RawValue()
			c.cache.pos++
			c.sst.pos++
		} else if ckey < tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.BooleanValue).RawValue()
			c.cache.pos++
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos++
		}

		pos++

		if c.sst.pos >= len(tvals.Timestamps) {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		if c.sst.pos < len(tvals.Timestamps) {
			if pos == 0 && len(c.res.Timestamps) >= len(tvals.Timestamps) {
				// optimization: all points can be served from SST data because
				// we need the entire block and the block completely fits within
				// the buffer.
				copy(c.res.Timestamps, tvals.Timestamps)
				pos += copy(c.res.Values, tvals.Values)
				c.nextSST()
			} else {
				// copy as much as we can
				n := copy(c.res.Timestamps[pos:], tvals.Timestamps[c.sst.pos:])
				copy(c.res.Values[pos:], tvals.Values[c.sst.pos:])
				pos += n
				c.sst.pos += n
				if c.sst.pos >= len(tvals.Timestamps) {
					c.nextSST()
				}
			}
		}

		if c.cache.pos < len(cvals) {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos < len(cvals) {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.BooleanValue).RawValue()
				pos++
				c.cache.pos++
			}
		}
	}

	// Strip timestamps from after the end time.
	if pos > 0 && c.res.Timestamps[pos-1] > c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] > c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *BooleanArrayAscendingCursor) nextSST() *types.BooleanArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadBooleanArrayBlock(c.sst.buf)
	c.sst.pos = 0
	return c.sst.values
}

type BooleanArrayDescendingCursor struct {
	cache struct {
		values types.Values
		pos    int
	}

	sst struct {
		buf       *types.BooleanArray
		values    *types.BooleanArray
		pos       int
		keyCursor *store.KeyCursor
	}

	end int64
	res *types.BooleanArray
}

func NewBooleanArrayDescendingCursor() *BooleanArrayDescendingCursor {
	c := &BooleanArrayDescendingCursor{
		res: types.NewBooleanArrayLen(config.DefaultMaxPointsPerBlock),
	}
	c.sst.buf = types.NewBooleanArrayLen(config.DefaultMaxPointsPerBlock)
	return c
}

func (c *BooleanArrayDescendingCursor) Reset(seek, end int64, cacheValues types.Values, sstKeyCursor *store.KeyCursor) {
	// Search for the time value greater than the seek time (not included)
	// and then move our position back one which will include the values in
	// our time range.
	c.end = end
	c.cache.values = cacheValues
	c.cache.pos = sort.Search(len(c.cache.values), func(i int) bool {
		return c.cache.values[i].UnixNano() > seek
	})
	c.cache.pos--

	c.sst.keyCursor = sstKeyCursor
	c.sst.values, _ = c.sst.keyCursor.ReadBooleanArrayBlock(c.sst.buf)
	c.sst.pos = sort.Search(c.sst.values.Len(), func(i int) bool {
		return c.sst.values.Timestamps[i] > seek
	})
	c.sst.pos--
}

func (c *BooleanArrayDescendingCursor) Err() error { return nil }

func (c *BooleanArrayDescendingCursor) Close() {
	if c.sst.keyCursor != nil {
		c.sst.keyCursor.Close()
		c.sst.keyCursor = nil
	}
	c.cache.values = nil
	c.sst.values = nil
}

func (c *BooleanArrayDescendingCursor) Next() *types.BooleanArray {
	pos := 0
	cvals := c.cache.values
	tvals := c.sst.values

	c.res.Timestamps = c.res.Timestamps[:cap(c.res.Timestamps)]
	c.res.Values = c.res.Values[:cap(c.res.Values)]

	for pos < len(c.res.Timestamps) && c.sst.pos >= 0 && c.cache.pos >= 0 {
		ckey := cvals[c.cache.pos].UnixNano()
		tkey := tvals.Timestamps[c.sst.pos]
		if ckey == tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.BooleanValue).RawValue()
			c.cache.pos--
			c.sst.pos--
		} else if ckey > tkey {
			c.res.Timestamps[pos] = ckey
			c.res.Values[pos] = cvals[c.cache.pos].(types.BooleanValue).RawValue()
			c.cache.pos--
		} else {
			c.res.Timestamps[pos] = tkey
			c.res.Values[pos] = tvals.Values[c.sst.pos]
			c.sst.pos--
		}

		pos++

		if c.sst.pos < 0 {
			tvals = c.nextSST()
		}
	}

	if pos < len(c.res.Timestamps) {
		// cache was exhausted
		if c.sst.pos >= 0 {
			for pos < len(c.res.Timestamps) && c.sst.pos >= 0 {
				c.res.Timestamps[pos] = tvals.Timestamps[c.sst.pos]
				c.res.Values[pos] = tvals.Values[c.sst.pos]
				pos++
				c.sst.pos--
				if c.sst.pos < 0 {
					tvals = c.nextSST()
				}
			}
		}

		if c.cache.pos >= 0 {
			// SST was exhausted
			for pos < len(c.res.Timestamps) && c.cache.pos >= 0 {
				c.res.Timestamps[pos] = cvals[c.cache.pos].UnixNano()
				c.res.Values[pos] = cvals[c.cache.pos].(types.BooleanValue).RawValue()
				pos++
				c.cache.pos--
			}
		}
	}

	// Strip timestamps from before the end time.
	if pos > 0 && c.res.Timestamps[pos-1] < c.end {
		pos -= 2
		for pos >= 0 && c.res.Timestamps[pos] < c.end {
			pos--
		}
		pos++
	}

	c.res.Timestamps = c.res.Timestamps[:pos]
	c.res.Values = c.res.Values[:pos]

	return c.res
}

func (c *BooleanArrayDescendingCursor) nextSST() *types.BooleanArray {
	c.sst.keyCursor.Next()
	c.sst.values, _ = c.sst.keyCursor.ReadBooleanArrayBlock(c.sst.buf)
	c.sst.pos = len(c.sst.values.Timestamps) - 1
	return c.sst.values
}
