// Code generated by tmpl; DO NOT EDIT.
// https://github.com/benbjohnson/tmpl
//
// Source: ./engine_cursor_build.gen.go.tmpl

package storage

import (
	"equinox/storage/cursor"
)

// buildFloatArrayCursor creates an array cursor for a float field.
func (e *Engine) buildFloatArrayCursor(key []byte, min, max int64, asc bool) cursor.FloatArrayCursor {
	cacheValues := e.mm.Values(key)
	if asc {
		keyCursor := e.keyCursor(key, min, asc)
		cur := cursor.NewFloatArrayAscendingCursor()
		cur.Reset(min, max, cacheValues, keyCursor)
		return cur
	} else {
		keyCursor := e.keyCursor(key, max, asc)
		cur := cursor.NewFloatArrayDescendingCursor()
		cur.Reset(max, min, cacheValues, keyCursor)
		return cur
	}
}

// buildIntegerArrayCursor creates an array cursor for a integer field.
func (e *Engine) buildIntegerArrayCursor(key []byte, min, max int64, asc bool) cursor.IntegerArrayCursor {
	cacheValues := e.mm.Values(key)
	if asc {
		keyCursor := e.keyCursor(key, min, asc)
		cur := cursor.NewIntegerArrayAscendingCursor()
		cur.Reset(min, max, cacheValues, keyCursor)
		return cur
	} else {
		keyCursor := e.keyCursor(key, max, asc)
		cur := cursor.NewIntegerArrayDescendingCursor()
		cur.Reset(max, min, cacheValues, keyCursor)
		return cur
	}
}

// buildUnsignedArrayCursor creates an array cursor for a unsigned field.
func (e *Engine) buildUnsignedArrayCursor(key []byte, min, max int64, asc bool) cursor.UnsignedArrayCursor {
	cacheValues := e.mm.Values(key)
	if asc {
		keyCursor := e.keyCursor(key, min, asc)
		cur := cursor.NewUnsignedArrayAscendingCursor()
		cur.Reset(min, max, cacheValues, keyCursor)
		return cur
	} else {
		keyCursor := e.keyCursor(key, max, asc)
		cur := cursor.NewUnsignedArrayDescendingCursor()
		cur.Reset(max, min, cacheValues, keyCursor)
		return cur
	}
}

// buildStringArrayCursor creates an array cursor for a string field.
func (e *Engine) buildStringArrayCursor(key []byte, min, max int64, asc bool) cursor.StringArrayCursor {
	cacheValues := e.mm.Values(key)
	if asc {
		keyCursor := e.keyCursor(key, min, asc)
		cur := cursor.NewStringArrayAscendingCursor()
		cur.Reset(min, max, cacheValues, keyCursor)
		return cur
	} else {
		keyCursor := e.keyCursor(key, max, asc)
		cur := cursor.NewStringArrayDescendingCursor()
		cur.Reset(max, min, cacheValues, keyCursor)
		return cur
	}
}

// buildBooleanArrayCursor creates an array cursor for a boolean field.
func (e *Engine) buildBooleanArrayCursor(key []byte, min, max int64, asc bool) cursor.BooleanArrayCursor {
	cacheValues := e.mm.Values(key)
	if asc {
		keyCursor := e.keyCursor(key, min, asc)
		cur := cursor.NewBooleanArrayAscendingCursor()
		cur.Reset(min, max, cacheValues, keyCursor)
		return cur
	} else {
		keyCursor := e.keyCursor(key, max, asc)
		cur := cursor.NewBooleanArrayDescendingCursor()
		cur.Reset(max, min, cacheValues, keyCursor)
		return cur
	}
}
